In [9]:
# Multi‑Layer Perceptron (MLP) – 1 Hidden Layer

"""
Concept
Forward: compute activations layer by layer.
Backward: back‑propagate error to update weights.
Code – Pure NumPy MLP
"""

import numpy as np

class MLP:
    def __init__(self, input_dim, hidden_dim, output_dim):
        self.W1 = np.random.randn(input_dim, hidden_dim) * 0.01
        # print("W1 = ", self.W1)
        self.b1 = np.zeros(hidden_dim)
        # print("b1 = ", self.b1) 
        self.W2 = np.random.randn(hidden_dim, output_dim) * 0.01
        # print("W2 = ", self.W2)
        self.b2 = np.zeros(output_dim)
        # print("b2 = ", self.b2)

    def relu(self, z):
        return np.maximum(0, z)

    def relu_deriv(self, z):
        return (z > 0).astype(float)

    def forward(self, x):
        self.z1 = x @ self.W1 + self.b1
        # print("z1 = ", self.z1)
        self.a1 = self.relu(self.z1)
        # print("a1 = ", self.a1)
        self.z2 = self.a1 @ self.W2 + self.b2
        # print("z2 = ", self.z2)
        return self.z2  # linear output

    def compute_loss(self, y_hat, y_true):
        return ((y_hat - y_true) ** 2).mean()

    def backward(self, x, y_true, y_hat):
        m = x.shape[0]
        dZ2 = (y_hat - y_true) / m
        dW2 = self.a1.T @ dZ2
        db2 = dZ2.sum(axis=0)

        dA1 = dZ2 @ self.W2.T
        dZ1 = dA1 * self.relu_deriv(self.z1)
        dW1 = x.T @ dZ1
        db1 = dZ1.sum(axis=0)

        return dW1, db1, dW2, db2

    def update(self, grads, lr=0.01):
        dW1, db1, dW2, db2 = grads
        self.W1 -= lr * dW1
        self.b1 -= lr * db1
        self.W2 -= lr * dW2
        self.b2 -= lr * db2

# Example: XOR problem
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])  # XOR labels

mlp = MLP(2, 4, 1)

for epoch in range(5000):
    y_hat = mlp.forward(X)
    loss = mlp.compute_loss(y_hat, Y)
    grads = mlp.backward(X, Y, y_hat)
    mlp.update(grads, lr=0.1)
    if epoch % 500 == 0:
        print(f"Epoch {epoch}, loss {loss:.4f}")

print("Final predictions:")
print(mlp.forward(X).round())

"""
# Gradient Descent & Optimizers
# Classic SGD

lr = 0.01
for epoch in range(epochs):
    # forward, loss, backward
    grads = mlp.backward(...)
    # update
    mlp.update(grads, lr)

# Momentum (Nesterov)

vW1, vb1, vW2, vb2 = 0, 0, 0, 0
momentum = 0.9
for epoch in range(epochs):
    grads = mlp.backward(...)
    vW1 = momentum * vW1 + grads[0]
    vb1 = momentum * vb1 + grads[1]
    # ... same for W2,b2
    mlp.W1 -= lr * vW1
    # ...

# Adam – The “default”

# Using PyTorch’s Adam is easiest; but you can implement:
# m = beta1 * m + (1-beta1) * grad
# v = beta2 * v + (1-beta2) * grad^2
# step = lr * m_hat / sqrt(v_hat + eps)

"""

W1 =  [[ 0.00231609 -0.01391472 -0.00333049  0.01191115]
 [-0.01849026 -0.0095301   0.00887792 -0.00493216]]
b1 =  [0. 0. 0. 0.]
W2 =  [[ 0.00336128]
 [-0.00584352]
 [-0.01267911]
 [-0.00714822]]
b2 =  [0.]
z1 =  [[ 0.          0.          0.          0.        ]
 [-0.01849026 -0.0095301   0.00887792 -0.00493216]
 [ 0.00231609 -0.01391472 -0.00333049  0.01191115]
 [-0.01617416 -0.02344482  0.00554743  0.006979  ]]
a1 =  [[0.         0.         0.         0.        ]
 [0.         0.         0.00887792 0.        ]
 [0.00231609 0.         0.         0.01191115]
 [0.         0.         0.00554743 0.006979  ]]
z2 =  [[ 0.00000000e+00]
 [-1.12564088e-04]
 [-7.73584857e-05]
 [-1.20223868e-04]]
Epoch 0, loss 0.5001
z1 =  [[ 8.40385692e-05  0.00000000e+00 -3.17051451e-04 -1.78740763e-04]
 [-1.84062184e-02 -9.53010463e-03  8.24381669e-03 -5.11092098e-03]
 [ 2.48417066e-03 -1.39147183e-02 -3.64757697e-03  1.15536730e-02]
 [-1.60060863e-02 -2.34448230e-02  4.91329117e-03  6.62149275e-03]]
a1 =  [[